# Generated by Django 4.0.5 on 2022-07-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coder_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('modalidad', models.CharField(max_length=40)),
                ('camada', models.IntegerField()),
            ],
        ),
    ]
